name: run-test-saidai

on:
  push:
    branches:
      - main  # ブランチ名が "main" の場合（"master" なら変更）

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Give execute permission
        run: chmod +x saidaikouyakusu.sh test-saidai.sh

      - name: Run test script
        run: ./test-saidai.sh

